version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - wget https://mirrors.estointernet.in/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
      - tar -xvf apache-maven-3.6.3-bin.tar.gz
      - mv apache-maven-3.6.3 /opt/
  pre_build:
    commands:
      - M2_HOME='/opt/apache-maven-3.6.3'
      - PATH="$M2_HOME/bin:$PATH"
      - export PATH
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - 'target/spring-ecom.war'
    - 'appspec.yml'
    - 'scripts/*.*'