server:
  port: '8080'

spring:
  profiles:
    active: qa
---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/ecomapp
    username: root
    password: StepWISE@1
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: 'true'

welcome:
  message: Hello! welcome to Spring Ecom.

---

spring:
  profiles: qa
  datasource:
    url: jdbc:mysql://spring-ecom-db.ct22tevwiyww.us-east-1.rds.amazonaws.com:3306/ecomapp
    username: admin
    password: SpringAWS
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: 'true'

welcome:
  message: Hello! welcome to Spring Ecom QA.

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
